language: python
python:
  - "3.8.1"
# command to install dependencies
install:
  - pip install -r requirements.txt

# database to use
env: DJANGO_SETTINGS_MODULE=pur_beurre.travis

os: windows
# command to run tests
script:
  - python manage.py test